# Leetcode 389//Easy
# Lintcode 1266//Easy//Google

# Description
# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example

# Input：s = "abcd"，t = "abcde"
# Output：'e'
# Explanation：'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # Questions to ask:
        # 1. Can s contain duplicated letters?
        s_letter_counts = dict()
        for l in s:
            if l not in s_letter_counts:
                s_letter_counts[l] = 0
            s_letter_counts[l] += 1
        for l in t:
            if l not in s_letter_counts:
                return l
            s_letter_counts[l] -= 1
        for (l, c) in s_letter_counts.items():
            if c == -1: # 一开始写成了1
                return l
